-$ https://github.com/on-aplikasi-android/TutorialUpdate.io.git
-$ add username.index.io
-$ echo"Hello word">index.io
-$ add api.codacy.com
-$ [![Codacy Badge](https://api.codacy.com/project/badge/Grade/d5154652a47442ceb3ae1f4a6ec8f843)
-$ git add --all
-$ git commit -m "Initial commit"
-$ git push -u origin master
